# Site settings
title: Editorial
subtitle: by HTML5 UP
email: 
description: 
baseurl: 
url: "https://petit-coder.github.io/" 
author: Hailyn
street_address: 
city:
state: 
zip_code: 
country: South Korea
phone: 
remote_theme : andrewbanchich/editorial-jekyll-theme
# Social settings
500px_url:
facebook_url:
github_url:
gitlab_url: 
googleplus_url: 
instagram_url: 
linkedin_url: 
pinterest_url:
slack_url:
twitter_url: 
# Build settings
markdown: kramdown
